locations = Location.create([
  {
  name: 'Center for Mental Health: Crisis Walk-In Crisis Center',
  phone: 3034250300,
  street: '4643 Wadsworth Blvd',
  city: 'Wheat Ridge',
  state: 'CO',
  zip: 80033,
  office_hours: '24/7',
  lat: 39.7807,
  lng: -105.0828,
  website: 'https://www.centermh.org/crisis-walk-in-center/',
  logo: 'https://github.com/CSheesley/ccs-frontend/blob/all-centers-pg/src/assets/images/center-logos/wheatridge-logo.png?raw=true'
  },
  {
  name: 'AllHealth Network Crisis Walk-In Center',
  phone: 3037303303,
  street: '6509 S Santa Fe Dr',
  city: 'Littleton',
  state: 'CO',
  zip: 80120,
  office_hours: '24/7',
  lat: 39.5982,
  lng: -105.0218,
  website: 'https://www.allhealthnetwork.org/services/crisis-services/',
  logo: 'https://github.com/CSheesley/ccs-frontend/blob/all-centers-pg/src/assets/images/center-logos/littleton-logo.png?raw=true'
  },
  {
  name: 'Mental Health Partners Walk-In Crisis Services',
  phone: 3034438500,
  street: '3180 Airport Rd',
  city: 'Boulder',
  state: 'CO',
  zip: 80301,
  office_hours: '24/7',
  lat: 40.0330,
  lng: -105.2338,
  website: 'https://www.mhpcolorado.org/crisis/',
  logo: 'https://github.com/CSheesley/ccs-frontend/blob/all-centers-pg/src/assets/images/center-logos/boulder-logo.png?raw=true'
  },
  {
  name: 'Mental Health Center of Denver',
  phone: 3035041299,
  street: '4353 E Colfax Ave',
  city: 'Denver',
  state: 'CO',
  zip: 80220,
  office_hours: '24/7',
  lat: 39.7403,
  lng: -104.9363,
  website: 'https://mhcd.org/suicide-prevention/',
  logo: 'https://github.com/CSheesley/ccs-frontend/blob/all-centers-pg/src/assets/images/center-logos/mhcd.jpg?raw=true'
  },
  {
  name: 'Aurora Walk-In Crisis Services',
  phone: 3036172300,
  street: '2206 Victor Street',
  city: 'Aurora',
  state: 'CO',
  zip: 80045,
  office_hours: '24/7',
  lat: 39.7491,
  lng: -104.8332,
  website: 'N/A',
  logo: 'https://github.com/CSheesley/ccs-frontend/blob/all-centers-pg/src/assets/images/CCS_Horizontal_Color.png?raw=true'
  },
  {
  name: 'SummitStone Walk-In Crisis Services',
  phone: 9704944200,
  street: '1217 Riverside Ave',
  city: 'Fort Collins',
  state: 'CO',
  zip: 80524,
  office_hours: '24/7',
  lat: 40.5754,
  lng: -105.0551,
  website: 'https://www.summitstonehealth.org/services/24-7-walk-in-crisis/',
  logo: 'https://github.com/CSheesley/ccs-frontend/blob/all-centers-pg/src/assets/images/center-logos/fort-collins-logo.png?raw=true'
  },
  {
  name: 'North Range Crisis Support Services',
  phone: 9703472120,
  street: '928 12th St',
  city: 'Greeley',
  state: 'CO',
  zip: 80631,
  office_hours: '24/7',
  lat: 40.4187,
  lng: -104.7030,
  website: 'https://northrange.org/services/crisis-support-services/',
  logo: 'https://github.com/CSheesley/ccs-frontend/blob/all-centers-pg/src/assets/images/center-logos/greeley.jpg?raw=true'
  },
  {
  name: 'Crisis Living Room: Emergency Crisis Services',
  phone: 7195452746,
  street: '1310 Chinook Ln',
  city: 'Pueblo',
  state: 'CO',
  zip: 81001,
  office_hours: '24/7',
  lat: 38.2904,
  lng: -104.6011,
  website: 'https://www.health.solutions/services/emergency-crisis-services/',
  logo: 'https://github.com/CSheesley/ccs-frontend/blob/all-centers-pg/src/assets/images/center-logos/pueblo-logo.png?raw=true'
  },
  {
  name: 'AspenPointe Walk-in Crisis Center',
  phone: 8444938255,
  street: '115 S Parkside Dr',
  city: 'Colorado Springs',
  state: 'CO',
  zip: 80910,
  office_hours: '24/7',
  lat: 38.8299,
  lng: -104.7859,
  website: 'https://www.aspenpointe.org/health-care-services/crisis-services-(text-call-walk-in)/crisis-stabilization-unit',
  logo: 'https://github.com/CSheesley/ccs-frontend/blob/all-centers-pg/src/assets/images/center-logos/colorado-springs-logo.png?raw=true'
  }
])
